WIP Debugging
TheGreenProphet/new-try-for-Vasic-Card-Game pull request #4
Opened 2017-12-04 19:55 UTC by julianbei

2017-12-04 20:06 UTC, julianbei commented
This should be fixed with this PR: 
#3

2017-12-05 18:01 UTC, TheGreenProphet approved these changes
got it

2017-12-05 18:12 UTC, TheGreenProphet approved these changes

2017-12-05 18:13 UTC, TheGreenProphet approved these changes

2017-12-05 18:14 UTC, TheGreenProphet approved these changes

2017-12-05 18:21 UTC, TheGreenProphet requested changes
Just added the card back again (don't know why it disapeared) and one could delete the missing image "feuerball" but actually it's there but called "Feuer"

2017-12-05 18:22 UTC, TheGreenProphet approved these changes

2017-12-05 18:23 UTC, merged